### ISSUE TITLE
tf.keras support

### ISSUE THREAD

**Issue by BrikerMan** [CyberZHG/keras-ordered-neurons#1]
**Is your feature request related to a problem? Please describe.**
Thanks a lot for your work, like keras-bert, keras-gpt-2 and this one.

I heavily benefited from your custom layers when I working with [Kashgari](https://github.com/BrikerMan/Kashgari ). Now I am planning to migrate Kashgari to tf.keras, so are you willing to maintain tf.keras version of these layers?

**Describe alternatives you've considered**
If you are not interested in maintaining tf.keras version, maybe I can help maintain the tf.keras version.

**Comment by CyberZHG** [comment]
I'm going to add tf.keras support in new repositories. However, I don't know if there is an easy way to maintain both versions since sometimes the only difference is in the import part. Do you have any suggestion?

**Comment by BrikerMan** [comment]
How about using the same repositories and pypi since they share lots of codes. Then import keras or tf.keras according to an environment variable / a global variable?

**Comment by CyberZHG** [comment]
I tried to add a backend file to another repo:

https://github.com/CyberZHG/keras-lr-multiplier/blob/3be5b8e0b92f34be600f4fcec3fcaae9ce264db8/keras_lr_multiplier/backend.py

It works but I'm not able to do the following imports:

```python
from .backend.optimizers import Adam
```

**Comment by BrikerMan** [comment]
You may need to use it like this

```python
import backend
print(backend.is_tf)
print(backend.optimizers)
print(backend.optimizers.Adam)
```
